# Generated by Django 2.0.6 on 2018-06-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_entry_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measuretype',
            old_name='measurement',
            new_name='measurment',
        ),
    ]
