# Generated by Django 2.0.6 on 2018-06-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180610_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='options',
            field=models.CharField(default={}, max_length=150),
            preserve_default=False,
        ),
    ]
